### ISSUE TITLE
String representation of the SofortTransaction model cannot be printed in Django shell

### ISSUE THREAD

**Issue by wh5a** [ParticulateSolutions/django-sofortueberweisung#1]
When asked to show a SofortTransaction model, the shell gave me

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/weihu/http/lib/python2.7/site-packages/django/db/models/base.py", line 572, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, __proxy__ found
```

Removing the ugettext_lazy calls from the `__unicode__` and the `__str__` functions fixed the problem.

**Comment by iekadou** [comment]
@wh5a I can not reproduce the bug, could you tell me more details?
